"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, <FULL NAME> and <FULL NAME>, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1:
UT EID 2:
"""


# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    if key <= 1 or key >= len(string):
        return string
    rails = ['' for _ in range(key)]
    rail = 0
    direction = 1
    for char in string:
        rails[rail] += char
        rail += direction
        if rail == 0 or rail == key - 1:
            direction *= -1
    return ''.join(rails)
 


# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    if key <= 1 or key >= len(string):
        return string
    rail_len = [0] * key
    rail = 0
    direction = 1
    for _ in string:
        rail_len[rail] += 1
        rail += direction
        if rail == 0 or rail == key - 1:
            direction *= -1
    rails = []
    idx = 0
    for rlen in rail_len:
        rails.append(string[idx:idx + rlen])
        idx += rlen
    result = ''
    rail = 0
    direction = 1
    pointers = [0] * key
    for _ in string:
        result += rails[rail][pointers[rail]]
        pointers[rail] += 1
        rail += direction
        if rail == 0 or rail == key - 1:
            direction *= -1
    return result



# TODO: implement this function. You may delete this comment after you are done.
def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    return ''.join(c.lower() for c in string if c.isalpha())



# TODO: implement this function. You may delete this comment after you are done.
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr((ord(p) - ord('a') + ord(s) - ord('a')) % 26 + ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    return chr((ord(s) - ord('a') - (ord(p) - ord('a')) + 26) % 26 + ord('a'))


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    text = filter_string(string)
    phrase = filter_string(phrase)
    if not text or not phrase:
        return ''
    phrase = (phrase * (len(string) // len(phrase) + 1))[:len(string)]
    return ''.join(encode_character(p, t) for p, t in zip(phrase, string))


# TODO: implement this function. You may delete this comment after you are done.
def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    string = filter_string(string)
    phrase = filter_string(phrase)
    if not string or not phrase:
        return ''
    phrase = (phrase * (len(string) // len(phrase) + 1))[:len(string)]
    return ''.join(decode_character(p, t) for p, t in zip(phrase, string))



# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher
    rf_plain = input("Enter plain text for Rail Fence: ")
    rf_key = int(input("Enter key: "))
    rf_encoded = rail_fence_encode(rf_plain, rf_key)
    print("Encoded (Rail Fence):", rf_encoded)

    rf_encoded_text = input("Enter encoded text for Rail Fence: ")
    rf_key2 = int(input("Enter key: "))
    rf_decoded = rail_fence_decode(rf_encoded_text, rf_key2)
    print("Decoded (Rail Fence):", rf_decoded)

    vig_plain = input("Enter plain text for Vigenere: ")
    vig_pass = input("Enter pass phrase: ")
    vig_encoded = vigenere_encode(vig_plain, vig_pass)
    print("Encoded (Vigenere):", vig_encoded)

    vig_encoded_text = input("Enter encoded text for Vigenere: ")
    vig_pass2 = input("Enter pass phrase: ")
    vig_decoded = vigenere_decode(vig_encoded_text, vig_pass2)
    print("Decoded (Vigenere):", vig_decoded)



# Do NOT modify the following code.
if __name__ == "__main__":
    main()
