"""
Student information for this assignment:

On my, Palash, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ppp625
"""


# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rails = ['' for _ in range(key)]
    rail, direction = 0, 1
    for char in string:
        rails[rail] += char
        rail += direction
        if rail == 0 or rail == key - 1:
            direction *= -1
    return ''.join(rails)



# TODO: implement this function. You may delete this comment after you are done.
def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    if key <= 1 or key >= len(string):
        return string
    pattern = [0] * len(string)
    rail, direction = 0, 1
    for i in range(len(string)):
        pattern[i] = rail
        rail += direction
        if rail == 0 or rail == key - 1:
            direction *= -1
    counts = [pattern.count(i) for i in range(key)]
    rails = []
    idx = 0
    for count in counts:
        rails.append(list(string[idx:idx+count]))
        idx += count
    result = []
    rail = 0
    direction = 1
    for i in range(len(string)):
        result.append(rails[pattern[i]].pop(0))
    return ''.join(result)


# TODO: implement this function. You may delete this comment after you are done.
def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    return ''.join(c for c in string.lower() if c.isalpha())



# TODO: implement this function. You may delete this comment after you are done.
def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    base = ord('A') if s.isupper() else ord('a')
    p_val = ord(p.lower()) - ord('a')
    s_val = ord(s.lower()) - ord('a')
    return chr((p_val + s_val) % 26 + base)


# TODO: implement this function. You may delete this comment after you are done.
def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    base = ord('A') if s.isupper() else ord('a')
    p_val = ord(p.lower()) - ord('a')
    s_val = ord(s.lower()) - ord('a')
    return chr((s_val - p_val + 26) % 26 + base)




# TODO: implement this function. You may delete this comment after you are done.
def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    phrase = filter_string(phrase)
    result = ''
    i = 0
    for c in string:
        if c.isalpha():
            result += encode_character(phrase[i % len(phrase)], c)
            i += 1
        else:
            result += c
    return result



# TODO: implement this function. You may delete this comment after you are done.
def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    phrase = filter_string(phrase)
    result = ''
    i = 0
    for c in string:
        if c.isalpha():
            result += decode_character(phrase[i % len(phrase)], c)
            i += 1
        else:
            result += c
    return result


# TODO: implement this function. You may delete this comment after you are done.
def main():
    """Main function that reads stdin and runs each cipher"""
    # read the plain text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # encrypt and print the encoded text using rail fence cipher

    # read encoded text from stdin (terminal/input)

    # read the key from stdin (terminal/input)

    # decrypt and print the plain text using rail fence cipher

    # read the plain text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # encrypt and print the encoded text using Vigenere cipher

    # read the encoded text from stdin (terminal/input)

    # read the pass phrase from stdin (terminal/input)

    # decrypt and print the plain text using Vigenere cipher
    print("Rail Fence Cipher")
    print()

    plain_text = input("Plain Text: ")
    key = int(input("Key: "))
    encoded = rail_fence_encode(plain_text, key)
    print("Encoded Text:", encoded)
    print()

    encoded_text = input("Encoded Text: ")
    key2 = int(input("Enter Key: "))
    decoded = rail_fence_decode(encoded_text, key2)
    print("Decoded Text:", decoded)
    print()

    print("Vigenere Cipher")
    print()

    plain_text = input("Plain Text: ")
    passphrase = input("Pass Phrase: ")
    encoded = vigenere_encode(plain_text, passphrase)
    print("Encoded Text:", encoded)
    print()

    encoded_text = input("Encoded Text: ")
    passphrase2 = input("Pass Phrase: ")
    decoded = vigenere_decode(encoded_text, passphrase2)
    print("Decoded Text:", decoded)



# Do NOT modify the following code.
if __name__ == "__main__":
    main()
