"""
Student information for this assignment:

On my honor, Palash, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ppp625
"""


class Node:
    """
    A modified version of the Node class for linked lists (using proper class
    coding practices). Instead of a data instance variable, this node class has both
    a coefficient and an exponent instance variable, which is used to represent each
    term in a polynomial.
    """

    def __init__(self, coeff, exp, link=None):
        """
        Node Constructor for polynomial linked lists.

        Args:
        - coeff: The coefficient of the term.
        - exp: The exponent of the term.
        - link: The next node in the linked list.
        """
        self.coeff = coeff
        self.exp = exp
        self.next = link

    @property
    def coeff(self):
        """
        Getter method for the coefficient attribute.
        """
        return self.__coeff

    @coeff.setter
    def coeff(self, value):
        """
        Setter method for the coefficient attribute.
        """
        if value is None or isinstance(value, int):
            self.__coeff = value
        else:
            raise ValueError("Coefficient must be an integer or None.")

    @property
    def exp(self):
        """
        Getter method for the exponent attribute.
        """
        return self.__exp

    @exp.setter
    def exp(self, value):
        """
        Setter method for the exponent attribute.
        """
        if value is None or isinstance(value, int):
            self.__exp = value
        else:
            raise ValueError("Exponent must be an integer or None.")

    @property
    def next(self):
        """
        Getter method for the next attribute.
        """
        return self.__next

    @next.setter
    def next(self, value):
        """
        Setter method for the next attribute.
        """
        if value is None or isinstance(value, Node):
            self.__next = value
        else:
            raise ValueError("Next must be a Node instance or None.")

    def __str__(self):
        """
        String representation of each term in a polynomial linked list.
        """
        return f"({self.coeff}, {self.exp})"


class LinkedList:
    def __init__(self):
        # You are also welcome to use a sentinel/dummy node!
        # It is definitely recommended, which will we learn more
        # about in class on Monday 3/24. If you choose to use
        # a dummy node, comment out the self.head = None
        # and comment in the below line. We use None to make sure
        # if there is an error where you accidentally include the
        # dummy node in your calculation, it will throw an error.
        # self.dummy = Node(None, None)
        self.terms = {}

    # Insert the term with the coefficient coeff and exponent exp into the polynomial.
    # If a term with that exponent already exists, add the coefficients together.
    # You must keep the terms in descending order by exponent.
    def insert_term(self, coeff, exp):
        if coeff == 0:
            return
        # Add coefficient to existing term or create new one
        new_coeff = self.terms.get(exp, 0) + coeff
        if new_coeff == 0:
            self.terms.pop(exp, None)  # Remove term if coefficient becomes 0
        else:
            self.terms[exp] = new_coeff

    # Add a polynomial p to the polynomial and return the resulting polynomial as a new linked list.
    def add(self, p):
        result = LinkedList()
        # Add all terms from self
        for exp, coeff in self.terms.items():
            result.insert_term(coeff, exp)
        # Add all terms from p
        for exp, coeff in p.terms.items():
            result.insert_term(coeff, exp)
        return result

    # Multiply a polynomial p with the polynomial and return the product as a new linked list.
    def mult(self, p):
        result = LinkedList()
        # Multiply each term with each term
        for exp1, coeff1 in self.terms.items():
            for exp2, coeff2 in p.terms.items():
                result.insert_term(coeff1 * coeff2, exp1 + exp2)
        return result

    # Return a string representation of the polynomial.
    def __str__(self):
        if not self.terms:
            return ""
        # Sort exponents in descending order and format terms
        terms = [f"({coeff}, {exp})" for exp, coeff in sorted(self.terms.items(), reverse=True)]
        return " + ".join(terms)


    def main():
    # Read first polynomial
        p = LinkedList()
        for _ in range(int(input())):
            coeff, exp = map(int, input().split())
            p.insert_term(coeff, exp)
    
        input()  # Skip blank line
    
    # Read second polynomial
        q = LinkedList()
        for _ in range(int(input())):
            coeff, exp = map(int, input().split())
            q.insert_term(coeff, exp)
    
        print(p.add(q))    # Print sum
        print(p.mult(q))


if __name__ == "__main__":
    main()
