"""
Student information for this assignment:

On my/our honor, Palash, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ppp625
"""

STEP_SIZE_CONSTANT = 3


# DO NOT modify this function.
def is_prime(n):
    """
    Determines if a number is prime.

    pre: n is a positive integer.
    post: Returns True if n is prime, otherwise returns False.
    """
    if n == 1:
        return False

    limit = int(n**0.5) + 1
    div = 2
    while div < limit:
        if n % div == 0:
            return False
        div += 1
    return True


# DO NOT modify this function.
def hash_word(s, size):
    """
    Hashes a lowercase string to an index in a hash table.

    pre: s is a lowercase string, and size is a positive integer representing either
         hash table size or the constant for double hashing.
    post: Returns an integer index in the range [0, size - 1] where the string hashes to.
    """
    hash_idx = 0
    for c in s:
        letter = ord(c) - 96
        hash_idx = (hash_idx * 26 + letter) % size
    return hash_idx


def step_size(s):
    """
    Calculates step size for double hashing using STEP_SIZE_CONSTANT.

    pre: s is a lowercase string.
    post: Returns the calculated step size as an integer based on the provided string.
    """
    return STEP_SIZE_CONSTANT - hash_word(s, STEP_SIZE_CONSTANT)


def insert_word(s, hash_table):
    """
    Inserts a string into the hash table using double hashing for collision resolution.
    No duplicates are allowed.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Inserts s into hash_table at the correct index; resolves any collisions
          by double hashing.
    """
    table_size = len(hash_table)
    index = hash_word(s, table_size)
    step = step_size(s)
    while hash_table[index] != "":
        if hash_table[index] == s:
            return  
        index = (index + step) % table_size
    hash_table[index] = s


def find_word(s, hash_table):
    """
    Searches for a string in the hash table.
    Note: using the `in` operator is incorrect as that will be O(N). We want
          an O(1) time average time complexity using hashing.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Returns True if s is found in hash_table, otherwise returns False.
    """
    table_size = len(hash_table)
    index = hash_word(s, table_size)
    step = step_size(s)
    start_index = index
    while hash_table[index] != "":
        if hash_table[index] == s:
            return True
        index = (index + step) % table_size
        if index == start_index:
            break
    return False


def is_reducible(s, hash_table, hash_memo):
    """
    Determines if a string is reducible using a recursive check.

    pre: s is a lowercase string, hash_table is a list representing the hash table,
         and hash_memo is a list representing the hash table
         for memoization.
    post: Returns True if s is reducible (also updates hash_memo by
          inserting s if reducible), otherwise returns False.
    """
    if s == "":
        return True

    if find_word(s, hash_memo):
        return True

    if not find_word(s, hash_table):
        return False

    for i in range(len(s)):
        subword = s[:i] + s[i+1:]
        if is_reducible(subword, hash_table, hash_memo):
            insert_word(s, hash_memo)
            return True

    return False


def get_longest_words(string_list):
    """
    Finds longest words from a list.

    pre: string_list is a list of lowercase strings.
    post: Returns a list of words in string_list that have the maximum length.
    """
    if not string_list:
        return []
    max_length = max(len(word) for word in string_list)
    longest_words = [word for word in string_list if len(word) == max_length]
    return longest_words


def main():
    """The main function that calculates the longest reducible words"""
    import sys

    # Read the words from input (each word on its own line)
    word_list = []
    for line in sys.stdin:
        word = line.strip()
        if word:  # Ensure word is not empty
            word_list.append(word)

    # Determine prime number N that is greater than twice the length of word_list.
    N = 2 * len(word_list) + 1
    while not is_prime(N):
        N += 1

    # Create an empty hash_table (dictionary) of size N, filled with blank strings.
    hash_table = ["" for _ in range(N)]
    # Insert each word from word_list into the hash_table using double hashing.
    for word in word_list:
        insert_word(word, hash_table)

    # Determine size M for the memoization hash table.
    # Let M be a prime number slightly greater than 0.2 * len(word_list).
    M_candidate = int(0.2 * len(word_list)) + 1
    while not is_prime(M_candidate):
        M_candidate += 1
    M = M_candidate

    # Create an empty hash_memo for memoizing reducible words.
    hash_memo = ["" for _ in range(M)]

    # Create a list to store reducible words.
    reducible_words = []
    for word in word_list:
        if is_reducible(word, hash_table, hash_memo):
            reducible_words.append(word)

    # Get the longest reducible words.
    longest_words = get_longest_words(reducible_words)
    # Print the longest reducible words in alphabetical order, one per line.
    for word in sorted(longest_words):
        print(word)


if __name__ == "__main__":
    main()
